openapi: 3.0.3
info:
  title: 帳戶管理服務 API
  description: |
    帳戶管理服務提供帳戶的新增、查詢、修改和刪除功能。
    支援多種帳戶類型包括現金、銀行帳戶、信用卡等。

    四模式差異化設計：
    - Expert: 完整帳戶分析功能、投資帳戶管理、多幣別支援
    - Inertial: 基本帳戶管理、簡化設定介面
    - Cultivation: 帳戶目標設定、儲蓄追蹤功能
    - Guiding: 帳戶建立導引、基礎餘額管理
  version: 1.0.0
  contact:
    name: LCAS 開發團隊
    email: dev@lcas.com

servers:
  - url: https://api.lcas.com/v1
    description: 生產環境
  - url: https://api-staging.lcas.com/v1
    description: 測試環境

paths:
  /accounts:
    get:
      tags:
        - 帳戶管理
      summary: 查詢帳戶清單
      description: |
        取得用戶的所有帳戶清單，支援分頁和篩選。
        四模式差異：
        - Expert: 顯示完整帳戶分析數據、投資績效
        - Inertial: 顯示基本帳戶資訊和餘額
        - Cultivation: 顯示目標達成進度、儲蓄統計
        - Guiding: 顯示簡化帳戶資訊、推薦操作
      parameters:
        - name: userId
          in: query
          required: true
          schema:
            type: string
          description: 用戶ID
        - name: page
          in: query
          schema:
            type: integer
            minimum: 1
            default: 1
          description: 頁碼
        - name: limit
          in: query
          schema:
            type: integer
            minimum: 1
            maximum: 100
            default: 20
          description: 每頁筆數
        - name: sort
          in: query
          schema:
            type: string
            enum: [name, balance, createdAt, updatedAt]
            default: createdAt
          description: 排序欄位
        - name: order
          in: query
          schema:
            type: string
            enum: [asc, desc]
            default: desc
          description: 排序方向
        - name: accountType
          in: query
          schema:
            type: string
            enum: [cash, bank, credit_card, digital_wallet, investment]
          description: 帳戶類型篩選
        - name: status
          in: query
          schema:
            type: string
            enum: [active, inactive, closed]
          description: 帳戶狀態篩選
      responses:
        '200':
          description: 成功取得帳戶清單
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/Account'
                  metadata:
                    type: object
                    properties:
                      pagination:
                        $ref: '#/components/schemas/PaginationInfo'
                      totalBalance:
                        type: number
                        description: 總餘額
                      accountCounts:
                        type: object
                        description: 各類型帳戶數量
        '400':
          description: 請求參數錯誤
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: 未授權
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: 伺服器錯誤
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

    post:
      tags:
        - 帳戶管理
      summary: 新增帳戶
      description: |
        建立新的帳戶。
        四模式差異：
        - Expert: 支援複雜帳戶設定、多幣別、投資帳戶
        - Inertial: 基本帳戶建立、預設設定
        - Cultivation: 支援目標設定、儲蓄計畫
        - Guiding: 引導式帳戶建立、推薦設定
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateAccountRequest'
      responses:
        '201':
          description: 帳戶建立成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  data:
                    $ref: '#/components/schemas/Account'
                  metadata:
                    type: object
                    properties:
                      message:
                        type: string
                        example: "帳戶建立成功"
        '400':
          description: 請求參數錯誤
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: 未授權
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '409':
          description: 帳戶已存在
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: 伺服器錯誤
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /accounts/{accountId}:
    get:
      tags:
        - 帳戶管理
      summary: 查詢單一帳戶
      description: |
        根據ID查詢特定帳戶資訊。
        四模式差異：
        - Expert: 顯示完整帳戶分析、交易歷史統計
        - Inertial: 顯示基本帳戶資訊
        - Cultivation: 顯示目標進度、趨勢分析
        - Guiding: 顯示簡化資訊、建議操作
      parameters:
        - name: accountId
          in: path
          required: true
          schema:
            type: string
          description: 帳戶ID
        - name: includeTransactions
          in: query
          schema:
            type: boolean
            default: false
          description: 是否包含交易記錄
        - name: includeAnalytics
          in: query
          schema:
            type: boolean
            default: false
          description: 是否包含分析數據
      responses:
        '200':
          description: 成功取得帳戶資訊
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  data:
                    $ref: '#/components/schemas/Account'
                  metadata:
                    type: object
                    properties:
                      transactionCount:
                        type: integer
                        description: 交易筆數
                      lastTransaction:
                        type: string
                        format: date-time
                        description: 最後交易時間
        '404':
          description: 帳戶不存在
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: 未授權
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: 伺服器錯誤
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

    put:
      tags:
        - 帳戶管理
      summary: 更新帳戶
      description: |
        更新帳戶資訊。
        四模式差異：
        - Expert: 支援完整帳戶設定修改
        - Inertial: 基本資訊修改
        - Cultivation: 支援目標調整
        - Guiding: 引導式設定修改
      parameters:
        - name: accountId
          in: path
          required: true
          schema:
            type: string
          description: 帳戶ID
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateAccountRequest'
      responses:
        '200':
          description: 帳戶更新成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  data:
                    $ref: '#/components/schemas/Account'
                  metadata:
                    type: object
                    properties:
                      message:
                        type: string
                        example: "帳戶更新成功"
                      changedFields:
                        type: array
                        items:
                          type: string
                        description: 異動欄位清單
        '400':
          description: 請求參數錯誤
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: 帳戶不存在
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: 未授權
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: 伺服器錯誤
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

    delete:
      tags:
        - 帳戶管理
      summary: 刪除帳戶
      description: |
        刪除指定的帳戶。僅允許刪除無交易記錄的帳戶。
        四模式差異：
        - Expert: 支援強制刪除選項、數據轉移
        - Inertial: 基本刪除功能
        - Cultivation: 刪除前影響評估
        - Guiding: 引導式刪除確認
      parameters:
        - name: accountId
          in: path
          required: true
          schema:
            type: string
          description: 帳戶ID
        - name: force
          in: query
          schema:
            type: boolean
            default: false
          description: 是否強制刪除（需要特殊權限）
      responses:
        '200':
          description: 帳戶刪除成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  data:
                    type: object
                    properties:
                      deletedAccountId:
                        type: string
                        description: 已刪除的帳戶ID
                  metadata:
                    type: object
                    properties:
                      message:
                        type: string
                        example: "帳戶已成功刪除"
        '404':
          description: 帳戶不存在
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: 未授權
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '409':
          description: 帳戶仍有交易記錄，無法刪除
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: 伺服器錯誤
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /accounts/{accountId}/balance:
    get:
      tags:
        - 帳戶管理
      summary: 查詢帳戶餘額
      description: |
        查詢指定帳戶的即時餘額資訊。
        四模式差異：
        - Expert: 顯示詳細餘額分析、歷史趨勢
        - Inertial: 顯示當前餘額
        - Cultivation: 顯示目標達成率
        - Guiding: 顯示簡化餘額資訊
      parameters:
        - name: accountId
          in: path
          required: true
          schema:
            type: string
          description: 帳戶ID
        - name: includeHistory
          in: query
          schema:
            type: boolean
            default: false
          description: 是否包含歷史餘額
      responses:
        '200':
          description: 成功取得餘額資訊
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  data:
                    type: object
                    properties:
                      currentBalance:
                        type: number
                        description: 當前餘額
                      availableBalance:
                        type: number
                        description: 可用餘額
                      pendingBalance:
                        type: number
                        description: 待處理餘額
                      currency:
                        type: string
                        description: 幣別
                      lastUpdated:
                        type: string
                        format: date-time
                        description: 最後更新時間
                  metadata:
                    type: object
                    properties:
                      balanceHistory:
                        type: array
                        items:
                          type: object
                        description: 餘額歷史（若包含）
        '404':
          description: 帳戶不存在
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: 未授權
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: 伺服器錯誤
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  schemas:
    Account:
      type: object
      properties:
        accountId:
          type: string
          description: 帳戶ID
        userId:
          type: string
          description: 用戶ID
        name:
          type: string
          description: 帳戶名稱
        type:
          type: string
          enum: [cash, bank, credit_card, digital_wallet, investment]
          description: 帳戶類型
        balance:
          type: number
          format: decimal
          description: 帳戶餘額
        availableBalance:
          type: number
          format: decimal
          description: 可用餘額
        currency:
          type: string
          default: "NTD"
          description: 幣別
        status:
          type: string
          enum: [active, inactive, closed]
          description: 帳戶狀態
        description:
          type: string
          description: 帳戶描述
        bankInfo:
          type: object
          description: 銀行資訊（銀行帳戶適用）
          properties:
            bankName:
              type: string
            accountNumber:
              type: string
            branchCode:
              type: string
        cardInfo:
          type: object
          description: 卡片資訊（信用卡適用）
          properties:
            cardNumber:
              type: string
            expiryDate:
              type: string
            cardLimit:
              type: number
        goals:
          type: object
          description: 帳戶目標（Cultivation模式）
          properties:
            targetBalance:
              type: number
            targetDate:
              type: string
              format: date
        createdAt:
          type: string
          format: date-time
          description: 建立時間
        updatedAt:
          type: string
          format: date-time
          description: 更新時間

    CreateAccountRequest:
      type: object
      required:
        - name
        - type
        - userId
      properties:
        name:
          type: string
          description: 帳戶名稱
          maxLength: 100
        type:
          type: string
          enum: [cash, bank, credit_card, digital_wallet, investment]
          description: 帳戶類型
        userId:
          type: string
          description: 用戶ID
        initialBalance:
          type: number
          format: decimal
          minimum: 0
          description: 初始餘額
        currency:
          type: string
          default: "NTD"
          description: 幣別
        description:
          type: string
          maxLength: 500
          description: 帳戶描述
        bankInfo:
          type: object
          description: 銀行資訊（銀行帳戶適用）
        cardInfo:
          type: object
          description: 卡片資訊（信用卡適用）
        goals:
          type: object
          description: 帳戶目標（Cultivation模式）

    UpdateAccountRequest:
      type: object
      properties:
        name:
          type: string
          description: 帳戶名稱
          maxLength: 100
        status:
          type: string
          enum: [active, inactive, closed]
          description: 帳戶狀態
        description:
          type: string
          maxLength: 500
          description: 帳戶描述
        bankInfo:
          type: object
          description: 銀行資訊
        cardInfo:
          type: object
          description: 卡片資訊
        goals:
          type: object
          description: 帳戶目標

    PaginationInfo:
      type: object
      properties:
        page:
          type: integer
          description: 當前頁碼
        limit:
          type: integer
          description: 每頁筆數
        total:
          type: integer
          description: 總筆數
        totalPages:
          type: integer
          description: 總頁數
        hasNext:
          type: boolean
          description: 是否有下一頁
        hasPrev:
          type: boolean
          description: 是否有上一頁

    ErrorResponse:
      type: object
      properties:
        success:
          type: boolean
          example: false
        error:
          type: object
          properties:
            code:
              type: string
              description: 錯誤代碼
            message:
              type: string
              description: 錯誤訊息
            field:
              type: string
              description: 錯誤欄位
            timestamp:
              type: string
              format: date-time
              description: 錯誤發生時間
            requestId:
              type: string
              description: 請求 ID
            details:
              type: object
              description: 詳細錯誤資訊
              properties:
                validation:
                  type: array
                  items:
                    type: object
                    properties:
                      field:
                        type: string
                      message:
                        type: string
                      value:
                        type: string