
// Mocks generated by Mockito 5.4.0 from annotations
// in apl_tests/8501. 認證服務_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// 引用主模組中的類型定義
import '../83. Flutter_Module code(API route)_APL/8301. 認證服務.dart' as _auth;

// Mock classes for authentication services
class MockAuthService extends _i1.Mock implements _auth.AuthService {
  MockAuthService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Future<_auth.RegisterResult> processRegistration(_auth.RegisterRequest request) =>
      (super.noSuchMethod(
        Invocation.method(#processRegistration, [request]),
        returnValue: _i2.Future<_auth.RegisterResult>.value(
          _auth.RegisterResult(userId: '', success: false),
        ),
      ) as _i2.Future<_auth.RegisterResult>);

  @override
  _i2.Future<_auth.LoginResult> authenticateUser(String email, String password) =>
      (super.noSuchMethod(
        Invocation.method(#authenticateUser, [email, password]),
        returnValue: _i2.Future<_auth.LoginResult>.value(
          _auth.LoginResult(success: false),
        ),
      ) as _i2.Future<_auth.LoginResult>);

  @override
  _i2.Future<void> processLogout(_auth.LogoutRequest request) =>
      (super.noSuchMethod(
        Invocation.method(#processLogout, [request]),
        returnValue: _i2.Future<void>.value(),
      ) as _i2.Future<void>);

  @override
  _i2.Future<void> initiateForgotPassword(String email) =>
      (super.noSuchMethod(
        Invocation.method(#initiateForgotPassword, [email]),
        returnValue: _i2.Future<void>.value(),
      ) as _i2.Future<void>);

  @override
  _i2.Future<_auth.ResetTokenValidation> validateResetToken(String token) =>
      (super.noSuchMethod(
        Invocation.method(#validateResetToken, [token]),
        returnValue: _i2.Future<_auth.ResetTokenValidation>.value(
          _auth.ResetTokenValidation(isValid: false, email: ''),
        ),
      ) as _i2.Future<_auth.ResetTokenValidation>);

  @override
  _i2.Future<void> executePasswordReset(String token, String newPassword) =>
      (super.noSuchMethod(
        Invocation.method(#executePasswordReset, [token, newPassword]),
        returnValue: _i2.Future<void>.value(),
      ) as _i2.Future<void>);

  @override
  _i2.Future<void> processEmailVerification(String email, String code) =>
      (super.noSuchMethod(
        Invocation.method(#processEmailVerification, [email, code]),
        returnValue: _i2.Future<void>.value(),
      ) as _i2.Future<void>);
}

class MockTokenService extends _i1.Mock implements _auth.TokenService {
  MockTokenService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Future<_auth.TokenPair> generateTokenPair(String userId, _auth.UserMode userMode) =>
      (super.noSuchMethod(
        Invocation.method(#generateTokenPair, [userId, userMode]),
        returnValue: _i2.Future<_auth.TokenPair>.value(
          _auth.TokenPair(
            accessToken: 'mock-token',
            refreshToken: 'mock-refresh',
            expiresAt: DateTime.now().add(Duration(hours: 1)),
          ),
        ),
      ) as _i2.Future<_auth.TokenPair>);

  @override
  _i2.Future<_auth.TokenValidationResult> validateRefreshToken(String token) =>
      (super.noSuchMethod(
        Invocation.method(#validateRefreshToken, [token]),
        returnValue: _i2.Future<_auth.TokenValidationResult>.value(
          _auth.TokenValidationResult(isValid: false),
        ),
      ) as _i2.Future<_auth.TokenValidationResult>);
}

class MockUserModeAdapter extends _i1.Mock implements _auth.UserModeAdapter {
  MockUserModeAdapter() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _auth.RegisterResponse adaptRegisterResponse(_auth.RegisterResult result, _auth.UserMode mode) =>
      (super.noSuchMethod(
        Invocation.method(#adaptRegisterResponse, [result, mode]),
        returnValue: _auth.RegisterResponse(
          userId: '',
          email: '',
          userMode: mode,
          verificationSent: false,
          needsAssessment: false,
          token: '',
          refreshToken: '',
          expiresAt: DateTime.now(),
        ),
      ) as _auth.RegisterResponse);

  @override
  _auth.LoginResponse adaptLoginResponse(_auth.LoginResult result, _auth.UserMode mode) =>
      (super.noSuchMethod(
        Invocation.method(#adaptLoginResponse, [result, mode]),
        returnValue: _auth.LoginResponse(
          token: '',
          refreshToken: '',
          expiresAt: DateTime.now(),
          user: _auth.UserProfile(
            id: '',
            email: '',
            displayName: '',
            userMode: mode,
            createdAt: DateTime.now(),
          ),
        ),
      ) as _auth.LoginResponse);
}

class MockSecurityService extends _i1.Mock implements _auth.SecurityService {
  MockSecurityService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool isPasswordSecure(String password) => (super.noSuchMethod(
        Invocation.method(#isPasswordSecure, [password]),
        returnValue: true,
      ) as bool);

  @override
  _i2.Future<bool> verifyPassword(String password, String hash) =>
      (super.noSuchMethod(
        Invocation.method(#verifyPassword, [password, hash]),
        returnValue: _i2.Future<bool>.value(true),
      ) as _i2.Future<bool>);

  @override
  _i2.Future<String> hashPassword(String password) => (super.noSuchMethod(
        Invocation.method(#hashPassword, [password]),
        returnValue: _i2.Future<String>.value('hashed-password'),
      ) as _i2.Future<String>);

  @override
  _i2.Future<String> generateSecureToken() => (super.noSuchMethod(
        Invocation.method(#generateSecureToken, []),
        returnValue: _i2.Future<String>.value('secure-token'),
      ) as _i2.Future<String>);

  @override
  bool validateTokenFormat(String token) => (super.noSuchMethod(
        Invocation.method(#validateTokenFormat, [token]),
        returnValue: true,
      ) as bool);
}

class MockValidationService extends _i1.Mock implements _auth.ValidationService {
  MockValidationService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_auth.ValidationError> validateRegisterRequest(_auth.RegisterRequest request) =>
      (super.noSuchMethod(
        Invocation.method(#validateRegisterRequest, [request]),
        returnValue: <_auth.ValidationError>[],
      ) as List<_auth.ValidationError>);
}

class MockErrorHandler extends _i1.Mock implements _auth.ErrorHandler {
  MockErrorHandler() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _auth.ApiError createValidationError(List<_auth.ValidationError> errors, _auth.UserMode mode) =>
      (super.noSuchMethod(
        Invocation.method(#createValidationError, [errors, mode]),
        returnValue: _auth.ApiError.create(_auth.AuthErrorCode.validationError, mode),
      ) as _auth.ApiError);
}

class MockModeConfigService extends _i1.Mock implements _auth.ModeConfigService {
  MockModeConfigService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _auth.ModeConfig getConfigForMode(_auth.UserMode mode) => (super.noSuchMethod(
        Invocation.method(#getConfigForMode, [mode]),
        returnValue: _auth.ModeConfig(
          mode: mode,
          settings: {},
          features: [],
        ),
      ) as _auth.ModeConfig);

  @override
  bool isFeatureEnabled(_auth.UserMode mode, String feature) => (super.noSuchMethod(
        Invocation.method(#isFeatureEnabled, [mode, feature]),
        returnValue: true,
      ) as bool);
}

class MockResponseFilter extends _i1.Mock implements _auth.ResponseFilter {
  MockResponseFilter() {
    _i1.throwOnMissingStub(this);
  }

  @override
  Map<String, dynamic> filterForExpert(Map<String, dynamic> data) =>
      (super.noSuchMethod(
        Invocation.method(#filterForExpert, [data]),
        returnValue: <String, dynamic>{},
      ) as Map<String, dynamic>);

  @override
  Map<String, dynamic> filterForInertial(Map<String, dynamic> data) =>
      (super.noSuchMethod(
        Invocation.method(#filterForInertial, [data]),
        returnValue: <String, dynamic>{},
      ) as Map<String, dynamic>);

  @override
  Map<String, dynamic> filterForCultivation(Map<String, dynamic> data) =>
      (super.noSuchMethod(
        Invocation.method(#filterForCultivation, [data]),
        returnValue: <String, dynamic>{},
      ) as Map<String, dynamic>);

  @override
  Map<String, dynamic> filterForGuiding(Map<String, dynamic> data) =>
      (super.noSuchMethod(
        Invocation.method(#filterForGuiding, [data]),
        returnValue: <String, dynamic>{},
      ) as Map<String, dynamic>);
}

class MockJwtProvider extends _i1.Mock implements _auth.JwtProvider {
  MockJwtProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String generateToken(Map<String, dynamic> payload, Duration duration) =>
      (super.noSuchMethod(
        Invocation.method(#generateToken, [payload, duration]),
        returnValue: 'mock-jwt-token',
      ) as String);

  @override
  Map<String, dynamic> verifyToken(String token) => (super.noSuchMethod(
        Invocation.method(#verifyToken, [token]),
        returnValue: <String, dynamic>{},
      ) as Map<String, dynamic>);
}
